#!/bin/bash

read -p "Enter a username: " username
echo -n "Enter a password: "
read -s password
echo
read -p "Enter permission groups (comma delimited): " groups
if [ -z "$groups" ]; then
	groups="none"
fi
hash=`echo -n "$password" | openssl dgst -binary -sha1 | openssl base64`
echo "$username:{SHA}$hash:$groups"
