source :rubygems

gem 'httparty',      '~> 0.21.0'

group :development do
  gem 'jeweler',       '~> 1.8.3'
  gem 'yard'
  gem 'redcarpet'
end

group :test do
  gem 'rspec'
  gem 'webmock'
  gem 'simplecov'
end
